### ISSUE TITLE
Expected in: /usr/lib/libc++.1.dylib

### ISSUE THREAD

**Issue by GRSource** [juliansteenbakker/mobile_scanner#627]
When debug iOS11.0 and launch crash log:

**dyld: Symbol not found: __ZTISt18bad_variant_access
  Referenced from: /var/containers/Bundle/Application/3908D51F-C774-421C-93B9-A3502128F938/Runner.app/Runner
  Expected in: /usr/lib/libc++.1.dylib
 in /var/containers/Bundle/Application/3908D51F-C774-421C-93B9-A3502128F938/Runner.app/Runner**

and flutter doctor -v：
<img decoding="async" src="https://i.imgur.com/q3lPSZW.png" width="100%">

**Comment by letrungdo** [comment]
I can reproduce too on iOS 11.2.6

**Comment by letrungdo** [comment]
It work fine in version 2.1.0

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
