### ISSUE TITLE
Deprecate MLKit for iOS

### ISSUE THREAD

**Issue by navaronbracke** [juliansteenbakker/mobile_scanner#1225]
`mobile_scanner` currently uses MLKit on both iOS and Android.

However, for iOS there is a first-party library, namely the Vision API from Apple.
We already use this implementation for MacOS.

We should switch iOS over to use that implementation, which brings a bunch of improvements.
The following checklist lists the points that we should tackle when doing this migration:

- [ ] lower the iOS deployment target back to Flutter's default of 12.0, as Vision is supported on minimum iOS 11
- [ ] add back build support for arm64 iOS Simulators, which are unsupported on MLKit
- [ ] merge both the iOS and MacOS implementation sources, https://github.com/juliansteenbakker/mobile_scanner/issues/782
- [ ] add support for the scan window, using https://developer.apple.com/documentation/vision/vnimagebasedrequest/regionofinterest
- [ ] backfill the barcode capture data, which previously was automatically provided by MLKit

**Comment by P0labrD** [comment]
Hello @juliansteenbakker 
My project would very much benefit from this change, I thank you for it 🙏
If you need any help to fasten the new release, I'd be happy to help 🙂

**Comment by RutgerVleuten** [comment]
Just tested an integration of v7.0.0-beta.3, no issues found so-far ...  looking forward to the public release!

**Comment by dincerkizildere** [comment]
Hello, is there any specific date set for the general release of version 7.0.0?

**Comment by topdeveloper1219** [comment]
Oh....
where are you from @navaronbracke? Can you cooperate with us as soon as possible?

**Comment by navaronbracke** [comment]
@topdeveloper1219 Anyone is free to use the v7 beta. As for the issue with analyze image, I'd have to look into it. But if you do find why it isn't completing after the await, feel free to submit a pull request

**Comment by chenfisher** [comment]
@navaronbracke 
Exception in `analyzeImage`

`mobile_scanner: ^7.0.0-beta.3`

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MobileScannerBarcodeException(Could not create inference context)
#0      MethodChannelMobileScanner.analyzeImage (package:mobile_scanner/src/method_channel/mobile_scanner_method_channel.dart:191:9)
```

Thanks

**Comment by navaronbracke** [comment]
@chenfisher Thanks for the stacktrace! Do you have the sample file that this occurred with?

**Comment by navaronbracke** [comment]
@chenfisher Turns out that analyzeImage is not supported on the iOS Simulator: https://forums.developer.apple.com/forums/thread/696714

**Comment by ua741** [comment]
Is there any plan to deprecate MLKit for Android as well? F-droid currently doesn't allow any app with dependency on MLKit.
Related https://github.com/mrousavy/react-native-vision-camera/issues/2371

**Comment by navaronbracke** [comment]
@ua741 We currently do not have plans to deprecate MLKit for Android. If there is a viable alternative that provides significant improvements (ZXing for Android could be considered, but as stated in the linked thread, it is not as fast as MLKit), then that can be revisited.

**Comment by Mian-zeeshan** [comment]
whats problem [!] CocoaPods could not find compatible versions for pod "mobile_scanner":
  In Podfile:
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)

Specs satisfying the `mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by navaronbracke** [comment]
@Mian-zeeshan The error indicates `but they required a higher minimum deployment target`, so you need to raise your minimum deployment target for iOS or MacOS. What version of mobile_scanner are you using?

**Comment by johnvuko** [comment]
Hello, I have an error when I try to compile on android with 7.0.0-beta.6 (version 6 is working)

```
e: file:///Users/jonathan/.pub-cache/hosted/pub.dev/mobile_scanner-7.0.0-beta.6/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:604:79 Argument type mismatch: actual type is 'android.graphics.Bitmap.Config?', but 'android.graphics.Bitmap.Config' was expected.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile_scanner:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

```
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3 24D60 darwin-arm64, locale en-FR) [314ms]
    • Flutter version 3.29.0 on channel stable at /Users/jonathan/flutter_3_7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (11 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,042ms]
    • Android SDK at /Users/jonathan/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Android Studio (version 2024.1) [10ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
```

**Comment by navaronbracke** [comment]
@johnvuko That is fixed on develop, but not yet published

**Comment by LeopardHowl** [comment]
If the issue persists, downgrade mobile_scanner to a stable version.

If you need to patch the package yourself, copy the mobile_scanner package into your lib/ folder.

Modify MobileScanner.kt as needed.

Reference the local version in pubspec.yaml:

dependencies:
  mobile_scanner:
    path: ./lib/mobile_scanner

**Comment by navaronbracke** [comment]
@LeopardHowl That don't be needed. I'll publish a patch later today when I'm back at my desk

**Comment by navaronbracke** [comment]
@johnvuko We are in the process of preparing a fix for this for 7.0.0-beta.7

**Comment by navaronbracke** [comment]
@johnvuko upgrading to 7.0.0-beta.7 should fix the issue you are seeing.

**Comment by michaeljajou** [comment]
Any ETA on when this is going to be out of beta?

**Comment by juliansteenbakker** [comment]
> Any ETA on when this is going to be out of beta?

Version 7 will be ready for release once #1402 will be merged

**Comment by juliansteenbakker** [comment]
I have released a release candidate for version 7, v7.0.0-rc.1.

https://github.com/juliansteenbakker/mobile_scanner/releases/tag/v7.0.0-rc.1

**Comment by juliansteenbakker** [comment]
I'm closing this since it is implemented in v7 version
